### ISSUE TITLE
Caps Lock

### ISSUE THREAD

**Issue by Immunia** [sallesma/le-invasion#10]
On Elzeberith (Aurélie) PC, this window activate caps lock

**Comment by sallesma** [comment]
[MP à Elzeberith: C'était quoi le délire avec le caps lock ? Bruno a juste noté "On Elzeberith (Aurélie) PC, this window activate caps lock"]
[MP à Elzeberith: T'as plus d'infos ?]
[MP de Elzeberith: oui, à chaque fois que je vais sur la fenetre d'inva, ça me met en cap lock ensuite]
[MP de Elzeberith: du coup ça fait une erreur en lançant l'inva, puisque le jeu prend en compte comme si c'était écrit en majuscule]
[MP de Elzeberith: je sais pas si c'est clair]
[MP de Elzeberith: :/]
[MP à Elzeberith: Et si tu ouvres l'appli et que tu la fermes direct sans rien faire dessus, ça le fait aussi ?]
[MP de Elzeberith: je sais pas, je vais te dire ça là ]
[MP de Elzeberith: non ]
[MP de Elzeberith: :)]
[MP à Elzeberith: Cool]
[MP à Elzeberith: Et si tu trifouilles l'onglet "Main Tab" et que tu fermes ?]
[MP à Elzeberith: (Le but étant de localiser le truc le plus précisément possible)]
[MP de Elzeberith: non pas de soucis]
[MP de Elzeberith: si j'ouvre juste une map, pas de soucis]
[MP de Elzeberith: non plus]
[MP à Elzeberith: Donc c'est unquement quand tu envoies une inva ?]
[MP de Elzeberith: oui, que je touche aux paramètres pour envoyer en tout cas]
[MP à Elzeberith: C'est quel formulaire (Classique / Commando) ?]
[MP de Elzeberith: moi j'ai le classique]
[MP de Elzeberith: je crois]

**Comment by sallesma** [comment]
[MP à Elzeberith: Et si tu touches aux paramètres mais que tu n'envoie pas l'inva (que tu ne cliques pas la carte) ça le fait aussi ?]
[MP de Elzeberith: je teste]
[MP de Elzeberith: non ça le fait pas]
[MP de Elzeberith: si j'envoie pas]

**Comment by Immunia** [comment]
abandonné
