### ISSUE TITLE
Handle bad config

### ISSUE THREAD

**Issue by sallesma** [sallesma/le-invasion#17]
Both wrong login/password and wrong server/port.

server/port is quite easy since open() can return false if the socket could not be opened
login/password is harder to check because you have to parse received text for LOGIN_OK or LOGIN_NOT_OK

**Comment by sallesma** [comment]
Also check there is no duplicate code with TabMain.isValidNetConfig()

**Comment by sallesma** [comment]
First draft there 165730704e868ee399f3fe385333d9c6434ab3c2

**Comment by Immunia** [comment]
Ended, pop up on LOGIN_NOT_OK and YOU_DONT_EXIST, not possible to load map in login is not ok
