### ISSUE TITLE
Add mini-console to each map tab

### ISSUE THREAD

**Issue by sallesma** [sallesma/le-invasion#4]
So that we can keep an history of what has been sent to each map

**Comment by sallesma** [comment]
With time and command

**Comment by sallesma** [comment]
Maybe in logfiles...

**Comment by Immunia** [comment]
logfiles better

**Comment by sallesma** [comment]
[MP de Elzeberith: Bon alors moi perso je m'en servirai pas.]
 L'utilisateur a parlé, je close :p
