### ISSUE TITLE
Add a PlayerTab

### ISSUE THREAD

**Issue by sallesma** [sallesma/le-invasion#5]
With the possibility to send an invasion to the position of a player/pnj ? @Immunia

**Comment by sallesma** [comment]
&attaque player monster

**Comment by sallesma** [comment]
Si on peut récupérer la liste des joueurs en ligne, et une liste des monstres...

**Comment by Immunia** [comment]
pour le &attaque je ne suis pas certain que ça soit vraiment utile, on ne doit même pas pouvoir le faire sur un pnj

**Comment by Immunia** [comment]
C'est surtout utilisé actuellement parce que entrer des coordonnées différentes à chaque fois c'est trop lourd

**Comment by Immunia** [comment]
mais quoi que, avec la liste des joueurs ça peut se réfléchir

**Comment by Immunia** [comment]
Mais on ne l'a pas encore

**Comment by sallesma** [comment]
On doit pouvoir la récupérer puisque le site du jeu et celui de la CI arrivent à l'afficher

**Comment by Immunia** [comment]
invasion sur un joueur c'est bof je pense en fait, l'autre outils est plus puissant, rien ne sert de complexifier
